version: '3.7'

services:
  php-fpm:
    build:
      context: ./docker/php-fpm
    networks:
      - nginx_phpfpm
    volumes:
      - ./docker/php-fpm/php-fpm.conf:/etc/php5/php-fpm.conf
      - ./src:/var/www

  nginx:
    build:
      context: ./docker/nginx
    ports:
      - "80:80"
    volumes:
      - ./docker/nginx/etc-nginx/conf.d/:/etc/nginx/conf.d/
      - ./docker/nginx/etc-nginx/nginx.conf:/etc/nginx/nginx.conf
      - ./src:/var/www
    depends_on:
      - php-fpm
    networks:
      - nginx_phpfpm

networks:
  nginx_phpfpm:
